[
    "division by zero |***|     01:19      14.08.2022",
    "division by zero |***|     01:24      14.08.2022",
    "'>' not supported between instances of 'int' and 'list' |***|     01:24      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     02:08      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     07:14      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     07:39      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     10:50      14.08.2022",
    "('Connection aborted.', ConnectionResetError(10054, '\u0423\u0434\u0430\u043b\u0435\u043d\u043d\u044b\u0439 \u0445\u043e\u0441\u0442 \u043f\u0440\u0438\u043d\u0443\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0440\u0430\u0437\u043e\u0440\u0432\u0430\u043b \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0435\u0435 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435', None, 10054, None)) |***|     12:14      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026224B741C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     12:14      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     14:28      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     15:43      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     19:44      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=20) |***|     19:44      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000216A24CB370>, 'Connection to api.telegram.org timed out. (connect timeout=20)')) |***|     19:45      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     20:51      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2D742E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2D8DD30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2DB27C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2DA7FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2DB2AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2DB2610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2D8D7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000216A2D8DBE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:12      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     21:18      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     22:03      14.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     01:11      15.08.2022",
    "('Connection aborted.', ConnectionResetError(10054, '\u0423\u0434\u0430\u043b\u0435\u043d\u043d\u044b\u0439 \u0445\u043e\u0441\u0442 \u043f\u0440\u0438\u043d\u0443\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0440\u0430\u0437\u043e\u0440\u0432\u0430\u043b \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0435\u0435 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435', None, 10054, None)) |***|     02:08      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     03:14      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     14:16      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002327FCCC7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     14:17      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     14:43      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     15:9      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     15:34      15.08.2022",
    "'NoneType' object is not iterable |***|     15:39      15.08.2022",
    "'NoneType' object is not iterable |***|     15:39      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:40      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:42      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "'NoneType' object is not iterable |***|     15:43      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     15:48      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "'NoneType' object is not iterable |***|     16:28      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     16:33      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     16:48      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "'NoneType' object is not iterable |***|     17:07      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     17:13      15.08.2022",
    "'NoneType' object is not iterable |***|     18:57      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:58      15.08.2022",
    "'NoneType' object is not iterable |***|     18:59      15.08.2022",
    "'NoneType' object is not iterable |***|     18:59      15.08.2022",
    "'NoneType' object is not iterable |***|     18:59      15.08.2022",
    "'NoneType' object is not iterable |***|     18:59      15.08.2022",
    "'NoneType' object is not iterable |***|     18:59      15.08.2022",
    "'NoneType' object is not iterable |***|     18:59      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     21:38      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000147BC258640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     21:38      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     22:23      15.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) |***|     23:29      15.08.2022",
    "('Connection aborted.', ConnectionResetError(10054, '\u0423\u0434\u0430\u043b\u0435\u043d\u043d\u044b\u0439 \u0445\u043e\u0441\u0442 \u043f\u0440\u0438\u043d\u0443\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0440\u0430\u0437\u043e\u0440\u0432\u0430\u043b \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0435\u0435 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435', None, 10054, None)) |***|     00:29      16.08.2022",
    "('Connection aborted.', ConnectionResetError(10054, '\u0423\u0434\u0430\u043b\u0435\u043d\u043d\u044b\u0439 \u0445\u043e\u0441\u0442 \u043f\u0440\u0438\u043d\u0443\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0440\u0430\u0437\u043e\u0440\u0432\u0430\u043b \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0435\u0435 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435', None, 10054, None)) |***|     00:29      16.08.2022",
    "HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5378831917:AAFEesUktOsPqVrijR0ArA2l8XXmZftcQwc/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000147BCB39040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) |***|     00:30      16.08.2022"
]